---
application:
  name: "mavkeses"
  project: "mavkeses"
  organization: "QoveryCommunity"
routers:
- name: "main-mavkeses"
  routes:
  - application_name: "mavkeses"
    paths:
    - "/max"
    - "/atlagos"
